FROM microsoft/dotnet:2.2-sdk AS build

WORKDIR /home/app

COPY ./*.sln ./
COPY src/Services/Identity/Identity.API/Identity.API.csproj src/Services/Identity/Identity.API/

RUN for file in $(ls *.csproj); do mkdir -p src/Services/Identity/${file%.*}/ && mv $file src/Services/Identity/${file%.*}/; done

RUN dotnet restore

COPY . .

WORKDIR /home/app/Integration/

ENTRYPOINT ["dotnet", "test", "--verbosity=normal"]
